# This workflow will do a clean installation of node dependencies, cache/restore them, run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: CI

on:  
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.17.x, 16.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: ${{ !env.ACT && 'yarn' || '' }}
    - name: Setup Yarn
      run: npm install -g yarn
    - run: yarn test
    - name: Uninstall Yarn
      if: always()
      run: npm uninstall -g yarn
