# This workflow will build demo project and deploy it to https://rangle.github.io/radius-tracker/
# For more information see: https://github.com/marketplace/actions/deploy-to-github-pages

name: Build and Deploy

on:
  pull:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v2
      - name: Use Node.js  🚧
        uses: actions/setup-node@v2
        with:
          node-version: ${{ secrets.NODE_VERSION }}
          cache: ${{ !env.ACT && 'yarn' || '' }}
      - name: Install Yarn 🚧
        if: ${{ env.ACT }}
        run: npm install -g yarn
      - name: Build Demo 🛠
        run: yarn demo-build
      - name: Install Rsync 📚
        if: ${{ env.ACT }}
        run: apt-get update && apt-get install -y rsync
      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4.2.5
        with:
          branch: gh-pages
          folder: src/demo/build
          token: ${{ secrets.GITHUB_TOKEN }}
