# This workflow will build docs and deploy it to https://rangle.github.io/radius-tracker/
# For more information see: https://github.com/marketplace/actions/deploy-to-github-pages

name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v2
      - name: Install Yarn 🚧
        if: ${{ env.ACT }}
        run: npm install -g yarn
      - name: Install Rsync 📚
        if: ${{ env.ACT }}
        run: apt-get update && apt-get install -y rsync
      - name: Cache build artifacts 💾
        uses: actions/cache@v3
        id: cache
        with:
          key: ${{ runner.os }}-${{ hashFiles('src/docs/pages', 'src/docs/next.config.js', 'src/docs/theme.config.jsx') }}
          path: src/docs/out
      - name: Build Docs Site 📖
        if: steps.cache.outputs.cache-hit != 'true'
        run: yarn docs-build
      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4.2.5
        with:
          branch: gh-pages
          folder: src/docs/out
          token: ${{secrets.GITHUB_TOKEN}}
