# This workflow will build demo project and deploy it to https://rangle.github.io/radius-tracker/
# For more information see: https://github.com/marketplace/actions/deploy-to-github-pages

name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v2
      - name: Install Yarn 🚧
        if: ${{ env.ACT }}
        run: npm install -g yarn
      - name: Terraform Init 🏗
        run: terraform -chdir=${{ github.workspace }}/terraform init
      - name: Terraform Apply
        run: terraform -chdir=${{ github.workspace }}/terraform apply   
      - name: Build 🛠
        run: REACT_APP_API_URL=$(terraform -chdir=${{ github.workspace }}/terraform output -json listener_outputs | jq -r '.api_invoke_url') yarn demo-build
      - name: Install Rsync 📚
        if: ${{ env.ACT }}
        run: apt-get update && apt-get install -y rsync
      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4.2.5
        with:
          branch: gh-pages
          folder: src/demo/build
          token: ${{secrets.GITHUB_TOKEN}}
