# This workflow will build demo project and deploy it to https://rangle.github.io/radius-tracker/
# For more information see: https://github.com/marketplace/actions/deploy-to-github-pages

name: Build and Deploy

on:
  push:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v2
      - name: Setup Yarn 🏗
        run: npm install -g yarn
      - name: Build 🛠
        run: yarn demo-build
      - name: Install rsync 📚
        run: ${{ env.ACT && 'apt-get update && apt-get install -y rsync' || '' }}
      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4.2.5
        with:
          branch: gh-pages
          folder: src/demo/build # The folder the action should deploy.
